//{{NO_DEPENDENCIES}}
// Microsoft eMbedded Visual C++ generated include file.
// Used by GpxSonar.rc
//
#define IDD_ABOUTBOX                    100
#define IDS_EDIT                        102
#define IDD_GEOSONAR_DIALOG             102
#define IDS_TOOL                        103
#define IDR_MAIN_TOOL                   106
#define IDR_DOC_TOOL                    107
#define IDM_DOCLIST                     108
#define IDR_MAINFRAME                   128
#define IDB_CACHES                      129
#define IDD_GPX_FILE_INFO               129
#define IDB_FILTERS                     131
#define IDR_OPTIONS                     131
#define IDD_CENTER                      132
#define IDD_DIST_UNITS                  133
#define IDD_FILTER_CONTAINERS           134
#define IDD_FILTER_MGR                  135
#define IDD_FILTER_TYPES                136
#define IDD_CACHE_HINTS                 137
#define IDD_CACHE_FIELDNOTES            138
#define IDD_ROT13CONVERT                139
#define IDD_CACHE_TRAVEL_BUGS           140
#define IDD_MY_TRAVEL_BUGS              141
#define IDD_FILTER_DIST_BEARING         142
#define IDB_BEARINGS                    143
#define IDD_EXPORT_LOCS_SELECTION       143
#define IDD_CACHE_LISTS                 144
#define IDD_FILTER_IGNORED_LIST         145
#define IDD_FILTER_STRINGS              146
#define IDD_LIST_PREFERENCES            147
#define IDD_SEARCH                      148
#define IDD_FILTER_RATINGS              149
#define IDD_PERFORMANCE                 150
#define IDD_PROJECT                     151
#define IDD_ALIAS                       152
#define IDD_FIELDNOTESREPORTPREFS       153
#define IDD_MYCACHES                    154
#define IDD_MYCACHE                     155
#define IDD_LINE_EDIT                   156
#define IDD_TEXT_EDIT                   157
#define IDD_DATE_PICKER                 158
#define IDD_RATING                      159
#define IDD_TB_PROPERTIES               160
#define IDB_TB                          161
#define IDD_TYPE_AND_CONTAINER          161
#define IDB_STRINGS                     162
#define IDD_PREFERENCES                 162
#define IDB_COLUMNS                     163
#define IDD_CACHECATEGORY               163
#define IDD_WAYPOINTS                   164
#define IDB_WAYPOINT                    165
#define IDD_CACHECATEGORYEDITOR         165
#define IDD_WPT_PROPERTIES              166
#define IDD_CACHE_IMPORT                167
#define IDD_EXPORT_PREFS                168
#define IDI_PLAY                        171
#define IDI_RECORD                      172
#define IDC_HIDE_DISABLED               1000
#define IDC_CACHE_LIST                  1001
#define IDC_CACHELIST                   1002
#define IDC_TIMESTAMP                   1002
#define IDC_ENABLE_SEARCH               1003
#define IDC_OPTIONS                     1004
#define IDC_EXPORT_TYPES                1004
#define IDC_LAT_COMBO                   1005
#define IDC_LAT_DEG                     1006
#define IDC_TREE                        1006
#define IDC_SET_LOC                     1006
#define IDC_LAT_MIN_MMM                 1007
#define IDC_UNITS1                      1007
#define IDC_UNITS2                      1008
#define IDC_UNIGNOREALL                 1008
#define IDC_LONG_COMBO                  1009
#define IDC_UNITS3                      1009
#define IDC_DIFFICULTY                  1009
#define IDC_LONG_DEG                    1010
#define IDC_DIFF_OPER                   1010
#define IDC_LONG_MIN_MMM                1011
#define IDC_DIST                        1011
#define IDC_DIFF_LVL                    1011
#define IDC_HIDE_IGNORED                1012
#define IDC_TERRAIN                     1012
#define IDC_RELOAD_LAST_GPX             1012
#define IDC_EDIT_IGNORED                1013
#define IDC_TERR_OPER                   1013
#define IDC_DOUBLECLICK_CACHE_DETAILS   1013
#define IDC_HIDE_FOUND                  1014
#define IDC_TERR_LVL                    1014
#define IDC_CATEGORIES                  1014
#define ID_OK                           1015
#define IDC_CATEGORY                    1016
#define IDC_EXCLUSIVE_OPTIONS           1017
#define IDC_CAT_EDIT                    1017
#define IDC_EXCLUSIVE_OPTIONS2          1018
#define IDC_CAT                         1018
#define IDC_SHOW_ONLY                   1019
#define IDC_CATLIST                     1019
#define IDC_HINTS                       1020
#define IDC_LIST                        1021
#define IDC_UNIGNORE                    1022
#define IDC_ROT13                       1022
#define IDC_EXPORT_NAME                 1022
#define IDC_CONVERT                     1023
#define IDC_INSCOPE                     1023
#define IDC_USE_WAP_SITE                1024
#define IDC_GEO                         1025
#define IDC_COORDS                      1025
#define IDC_SPOILER_PICS_LOCATION       1025
#define IDC_NOTES                       1026
#define IDC_CONFIG                      1026
#define IDC_SPOILER_BROWSE              1026
#define IDC_STATUS                      1027
#define IDC_COLS                        1027
#define IDC_ExportMaxLimit              1027
#define IDC_STATUS2                     1028
#define IDC_TEXT                        1028
#define IDC_STATUS3                     1029
#define IDC_MATCH                       1029
#define IDC_RECORD                      1029
#define IDC_STATUS4                     1030
#define IDC_MATCH2                      1030
#define IDC_NO_IMG_TAGS                 1030
#define IDC_SAVE                        1031
#define IDC_EXPORT_OPTIONS              1031
#define IDC_DELETE                      1032
#define IDC_EXPORT                      1032
#define IDC_TB                          1033
#define IDC_COMMAND                     1033
#define IDC_CACHE_TB_LIST               1034
#define IDC_MemUsage                    1034
#define IDC_GO                          1034
#define IDC_MY_TB_LIST                  1035
#define IDC_PROJECT                     1035
#define IDC_RADIO2                      1035
#define IDC_GRAB                        1036
#define IDC_DROP                        1037
#define IDC_ADD                         1038
#define IDC_Units                       1038
#define IDC_REMOVE                      1039
#define IDC_EDIT                        1040
#define IDC_Bearing                     1040
#define IDC_IMPORT                      1041
#define IDC_SERIAL                      1041
#define IDC_TB_LIST                     1042
#define IDC_PREVIEW                     1042
#define IDC_Direction                   1042
#define IDC_NAME                        1042
#define IDC_Distance                    1043
#define IDC_LOCATION                    1043
#define IDC_AZIMUTH                     1044
#define IDC_REF                         1044
#define IDC_ALIAS                       1045
#define IDC_AZIMUTH2                    1045
#define IDC_FOUNDIT                     1046
#define IDC_NOTFOUND                    1047
#define IDC_ARCHIVE                     1049
#define IDC_NEW                         1051
#define IDC_CACHES                      1054
#define IDC_PROPERTIES                  1057
#define IDC_RATING                      1064
#define IDC_HTML                        1065
#define IDC_YEAR                        1066
#define IDC_MONTH                       1067
#define IDC_WPTS                        1067
#define IDC_DAY                         1069
#define IDC_COMMENT                     1070
#define IDC_COORDS_TEXT                 1071
#define IDC_SHOW_MINE                   1077
#define IDC_BOOKMARK                    1078
#define IDC_SELECT                      1079
#define ID_EXPORT2MERIDIAN              32771
#define ID_CACHE_DETAILS                32772
#define ID_LOAD_GPX                     32773
#define IDS_CAP_LIST                    32774
#define ID_MENU_FILTERS                 32775
#define ID_GPXFILEINFO                  32776
#define ID_MENU_SETASCENTER             32777
#define ID_MENU_LISTOPTIONS_CENTERCOORDS 32778
#define ID_MENU_LISTOPTIONS_PREFERENCES 32779
#define ID_MENU_CACHEOPTIONS_IGNORECACHE 32780
#define IDS_CAP_FILE                    32780
#define ID_FILE_EXIT                    32781
#define ID_MENU_FILE_PERFORMANCE        32782
#define ID_MENU_FILE_REPORTS_FIELDNOTES 32783
#define ID_MENU_FILE_MYCACHES           32784
#define ID_MENU_FILE_MYALIAS            32785
#define ID_FILTERS                      32786
#define ID_MENU_FILE_TOOLS_EXPORT_EXPORTTOLOCFILE 32787
#define ID_QUICK_SEARCH                 32788
#define ID_DISTANCE_UNITS               32789
#define ID_TOOLS_EXPORT_FIELDNOTES_TOGSAK 32790
#define ID_LOG_CACHE                    32791
#define ID_TOOLS_EXPORT_EXPORTLOCATIONS 32792
#define ID_TOOLS_EXPORT_WAYPOINTS_TOPHAROSOSTIA6 32794
#define ID_MENU_CACHEOPTIONS_SHOWHINTS  32795
#define ID_TOOLS_EXPORT_WAYPOINTS_TOMSSTPUSHPINS 32796
#define ID_MENU_FILE_ROT13HELPER        32797
#define ID_MENU_FILE_MYTRAVELBUGS       32798
#define ID_TOOLS_EXPORT_GEO             32799
#define ID_MENU_IGNORECACHESBYTHISOWNER 32800
#define ID_MENU_DISMISSMENU             32801
#define ID_FILE_APPCONFIG               32802
#define ID_TOOLS_EXPORT_WAYPOINTS_TOMAPTECHMXFFORMAT 32803
#define ID_TOOLS_EXPORT_EXPORTOPTIONS   32804
#define ID_TOOLS_EXPORT_WAYPOINTS_TOCSVFILE 32806
#define ID_TOOLS_FIELDNOTESCLEANER      32809
#define ID_TOOLS_EXPORT_WAYPOINTS_TOLOWRANCEIFINDER 32811
#define ID_TOOLS_EXPORT_WAYPOINTS_TOEXPLORISTSDFILE 32812
#define ID_TOOLS_EXPORT_WAYPOINTS_TOOZIEXPLORERFILE 32813
#define ID_MENU_EXPORT                  32815
#define IDS_NEW                         65000
#define IDS_FILE                        65001
#define IDS_MHELP                       65002
#define IDS_SAVE                        65003
#define IDS_CUT                         65004
#define IDS_COPY                        65005
#define IDS_PASTE                       65006

// Next default values for new objects
// 
#ifdef APSTUDIO_INVOKED
#ifndef APSTUDIO_READONLY_SYMBOLS
#define _APS_NEXT_RESOURCE_VALUE        174
#define _APS_NEXT_COMMAND_VALUE         32816
#define _APS_NEXT_CONTROL_VALUE         1035
#define _APS_NEXT_SYMED_VALUE           101
#endif
#endif
